### PR TITLE
Add node.js support for building/deploying proxies.

### PR DESCRIPTION
**Pull request by michaelarusso**

### CODE REVIEW

**Comment by michaelarusso** [comment]
Diff may be easier to see when using https://github.com/apigee/apigee-deploy-maven-plugin/pull/24/files?w=1  (w=1 ignores whitespace differences)

**Comment by michaelarusso** [comment]
I added additional support for node.js app code.  Some developers structure their workspace as follows:

````
├── apiproxy
│   ├── helloworld-express.xml
│   ├── proxies
│   ├── resources
│   └── targets
├── deploy.sh
├── node
│   ├── helloworld-express.js
│   └── node_modules
└── pom.xml
````

In this case, the node.js source code lives outside ```apiproxy/``` in the ```node/``` directory.  If we find this scenario, the plugin will now move the source from ```node/``` into ```/apiproxy/resources/node```  when building. It continues to handle the zipping of any node modules in  ```apiproxy/resources/node```.  If node.js source code exists in both ```apiproxy/resources/node``` and ```node/```, the source in ```node/``` takes precedence and will be used in the built and deployed API proxy bundle.

**Comment by DinoChiesa** [comment]
Michael, 
It seems with this change you are accommodating people who structure their directories incorrectly. It might be better to just issue an appropriate error message telling the developer to structure it properly. This maven tool may accommodate their error, but there will be other tools that do not. 

-DC

**Comment by michaelarusso** [comment]
@DinoChiesa I don't think it's an incorrect workspace since node apps can be standalone to Apigee proxies.  However, you do make me think there is a better way to handle this scenario more config driven if the node source code is not in ```apiproxy/resources/node```.  Reversing that commit and will table the better version for later.

**Pull request merged**
