### PR TITLE
Maven plugin HTTP proxy support and rework

### PR DESCRIPTION
**Pull request by bertramn**
Hi Apigee team,

the pull request tries to streamline a few things in the maven plugin and Rest client. The main issue we had was that the plugin would not work behind the corporate firewall. So we added a capability for the plugin to detect the standard proxy settings in the maven plugin context (as configured in the settings.xml) and use that to communicate to the Apigee gateway.

Along the way we did some refactoring of things and added some notes on other things that need attention. The full list of changes recorded below.

Please let us know if this is something you can incorporate.

**Cleanup and Refactor**
* added basic style configuration
* added git attribute configuration to prevent Microsoft Word documents to fall appart on *nix  based checkout
* code formatting is pretty loose
* added proper dependency management section to pom file
* fixed issue where the proxy bundle is missing a dash between project name and version
* default proxy bundle name to project.artefactId if project.name is not set
* fixed proxy bundle file name garbled with null if no profile is set
* updated gpg plugin to version 1.6
* added proper plugin management section
* updated compiler plugin to more recent version and set JDK level 1.6
* updated maven api to 3.1
* removed unused imports
* removed superflorus default constructors
* removed superflorus logger declaration and use
* removed verbose newline use from log statements
* half fixed logging to use slf4j and remove commons-logging
* removed old log4j 1 configuration
* declare log dependencies properly and removed redundant configuration files so they dont interfere with maven internals logging
* remove unnecessary this and super refrences
* used file parent constructor when creating file handles instead of stringifying things
* fixed debut output formatting in RestUtil
* simplify exception handing in all mojos and removing superflorus try/catch/finally blocks
* create server profile only once
* check that all auth args are provided in deploy mojo depending on basic or oauth type
* refactored ServerProfile and removed any execution type properties
* turned revision numbers into Long for easier comparison
* remove axis dependencies for dodgy fake hostname verifier, implementing the JRE interface suffices
* turned static RestUtil into an instance based RestClient cause it requires configuration to work
* replaced global params with invocation scoped immutable objects (e.g. for application name, revision and type)
* changed string concatenation of URLs to use a printf type format template
* replaced static global Options class and buildOption with enum set and moved delay to ServerProfile
* simplified delay code
* moved tests into the same package as the code they are testing
* updated tests to use anotations instead extending stuff from the dark ages
* added a base test class that sets up most integration test pre-requisites
* separated deployment actions to remove this hidiously long case and if-then-else statement in DeployMojo
* updated javadocs when touching function
* removed some try/catch nesting to allow exceptions to tricle up where someone can actually do something about them

**HTTP Proxy Support**
* updated google http client to 1.22.0
* added apache httpclient 4.0.3
* changed http client factory from JDK to http-commons to for proxy support
* injecting maven project and container so we can implement proxy support
* changed to apache httpclient for proxy support
* when a maven proxy is detected, the apache http client is created and handles the proxy connections
* removed RestUtil.java
* add switch to disable authentication context validation when not needed by maven plugin

**Upstream Merges**
* merged #80 from mikeleaver/patch-1
* merged #75

### CODE REVIEW

**Comment by bertramn** [comment]
Hey there, any update on this PR? Would be nice to have a plugin with http proxy support available from maven central.

**Comment by ssvaidyanathan** [comment]
We have customers using this plugin with proxy - there are many posts around this in Apigee community. Check [this](https://community.apigee.com/questions/39268/apigee-maven-plugin-behind-corporate-proxy.html) one for example

**Comment by bertramn** [comment]
Yeah no sorry buddy, this suggestion is not how Maven works and when proxy authentication is required this is **totally INSECURE** as we would see users passwords floating about in bash history and on build servers. Maven comes with this totally awesome feature called `/settings/proxies/proxy` ... that's what maven users should be using to configure proxy settings and that's what Maven plugins should be using to setup proxy connections. Maven even allows you to [encrypt passwords](https://maven.apache.org/guides/mini/guide-encryption.html) in the `settings.xml` file. No chance in hell we'd resort to passing sensitive information around in JVM args.

**Comment by bertramn** [comment]
No one looking into the PR, is this project maintained?

**Comment by patluri43** [comment]
Our Proxy needs basic auth and we are unable to pass authentication credentials via Maven Opts or Java Opts. This feature will really help us moving forward

**Comment by gredler** [comment]
I also need this feature. I see activity in this repo in the last few days, but it worries me that this PR has sat here for so long without feedback one way or the other. Can somebody at Apigee either merge this PR, explain what needs to change for it to be merged, or explain why it will never be merged?

@ssvaidyanathan

**Comment by ssvaidyanathan** [comment]
Created a new PR #112 as this is getting picked after a while. Once I have tested, will release this as a new version. 

Closing this one

@bertramn - Thanks for the PR again. Appreciate if you can look into the new one I opened and approve

**Pull request closed without merging**
