### PR TITLE
Plugin rework

### PR DESCRIPTION
**Pull request by ssvaidyanathan**
At last - got the time to pick it up as I plan to refactor this plugin to support Apigee Hybrid
Since there are lots of changes, creating a PR to another branch (instead of master)

For details on the changes, please refer to #83

### CODE REVIEW

**Comment by ssvaidyanathan** [comment]
@bertramn - Can you please follow the instructions provided by google bot, so that I can go ahead with the process. Thanks once again

**Comment by dstrachan1** [comment]
Hello Sai,

hope you are well.  Just wanted to ask about this merge as we are facing a problem whereby we cannot get the plugins (apigee-config and apigee-deploy) to work via a proxy server.   Thanks so much, Darren

**Comment by ssvaidyanathan** [comment]
@dstrachan1 - waiting for @bertramn to consent to the CLA after which I should be able to do it. 
In the interim, you could pass the HTTP_PROXY/HTTPS_PROXY as MAVEN_OPTS arguments and see if that helps

**Comment by dstrachan1** [comment]
Ok great thank you Sai

**Comment by dstrachan1** [comment]
Hi again Sai, I forgot to mention – I think the same problem exists in the apigee-config plugin… it was actually whilst trying to use that one we found this problem….
Thanks, Darren

**Comment by ssvaidyanathan** [comment]
Sure - once this is merged. I will try and push similar logic to the config plugin. For now, please use the MAVEN_OPTS I suggested

**Comment by dstrachan1** [comment]
So we think it’s no different from specifying using -D on the command line, which we already tried...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ssvaidyanathan** [comment]
Yes. Did you get it to work by passing ?

**Comment by dstrachan1** [comment]
No, unfortunately not.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bertramn** [comment]
@googlebot I consent.

**Pull request merged**
