### PR TITLE
add config file path and application bundle parameters and use projec…

### PR DESCRIPTION
**Pull request by warrenc5**
changed the author and reset the last commit.

### CODE REVIEW

**Comment by warrenc5** [comment]
google-bot - where art thou?

**Comment by warrenc5** [comment]
Hi thanks, for responding, I have tried to make this plugin more compatible with maven project directory structure, specifically able to locate the config.json file within the target dir.  We are maven resource filtering the config.json before configuring the bundle.

**Comment by warrenc5** [comment]
actually this solves https://github.com/apigee/apigee-deploy-maven-plugin/issues/93

**Comment by ssvaidyanathan** [comment]
Thanks @warrenc5 - can you also include changes to the README file so that I can see what has changed end to end. Update the samples so that we could use that as well for testing the features built.

**Pull request closed without merging**
